with open('frontend/app/farmer/pages/SharedLoginPage.tsx', 'r', encoding='utf-8') as f:
    content = f.read()

# Build registration JSX using list of lines (avoids backtick shell issues)
BT = chr(96)  # backtick character
DQ = chr(34)  # double quote
SQ = chr(39)  # single quote

lines = []
lines.append("                )}")
lines.append("")
lines.append("                {/* REGISTER MODE - Multi-Step */}")
lines.append("{authMode === " + SQ + "register" + SQ + " && (")
lines.append("<form onSubmit={handleRegisterSubmit} className=" + DQ + "space-y-4" + DQ + ">")
lines.append("<div className=" + DQ + "flex items-center justify-center gap-2 text-xs" + DQ + ">")
lines.append("{[1,2,3,4].map(s => (")
lines.append("<div key={s} className=" + BT + "${regStep >= s ? " + SQ + "text-emerald-700 font-bold" + SQ + " : " + SQ + "text-slate-400" + SQ + "} flex items-center gap-1" + BT + ">")
lines.append("<span className=" + BT + "w-6 h-6 rounded-full flex items-center justify-center text-[10px] border ${regStep >= s ? " + SQ + "bg-emerald-700 text-white border-emerald-700" + SQ + " : " + SQ + "border-slate-300" + SQ + "}" + BT + ">{s}</span>")
lines.append("<span className=" + DQ + "hidden sm:inline" + DQ + ">{s===1?" + SQ + "Details" + SQ + ":s===2?" + SQ + "Location" + SQ + ":s===3?" + SQ + "Farm" + SQ + ":" + SQ + "Crops" + SQ + "}</span>")
lines.append("{s < 4 && <span className=" + DQ + "text-slate-300 mx-1" + DQ + ">-</span>}")
lines.append("</div>))}</div>")
lines.append("{regStep === 1 && (<div className=" + DQ + "space-y-3" + DQ + ">")
lines.append("<div><label className=" + DQ + "block text-xs font-bold uppercase tracking-wider text-slate-700 mb-1" + DQ + ">Full Name *</label><input type=" + DQ + "text" + DQ + " required value={regName} onChange={e => setRegName(e.target.value)} placeholder=" + DQ + "e.g. Ravi Kumar" + DQ + " className=" + DQ + "input-field text-sm" + DQ + " /></div>")
lines.append("<div><label className=" + DQ + "block text-xs font-bold uppercase tracking-wider text-slate-700 mb-1" + DQ + ">Email *</label><input type=" + DQ + "email" + DQ + " required value={regEmail} onChange={e => setRegEmail(e.target.value)} placeholder=" + DQ + "ravi@example.com" + DQ + " className=" + DQ + "input-field text-sm" + DQ + " /></div>")
lines.append("<div><label className=" + DQ + "block text-xs font-bold uppercase tracking-wider text-slate-700 mb-1" + DQ + ">Password *</label><input type=" + DQ + "password" + DQ + " required value={regPassword} onChange={e => setRegPassword(e.target.value)} placeholder=" + DQ + "Min 6 characters" + DQ + " className=" + DQ + "input-field text-sm" + DQ + " /></div>")
lines.append("<div><label className=" + DQ + "block text-xs font-bold uppercase tracking-wider text-slate-700 mb-1" + DQ + ">Phone Number</label><input type=" + DQ + "tel" + DQ + " value={regPhone} onChange={e => setRegPhone(e.target.value)} placeholder=" + DQ + "9876543210" + DQ + " className=" + DQ + "input-field text-sm" + DQ + " /></div>")
lines.append("<button type=" + DQ + "button" + DQ + " onClick={() => setRegStep(2)} className=" + DQ + "btn-primary w-full py-3 text-sm font-bold bg-emerald-800 hover:bg-emerald-900" + DQ + ">Next: Location</button>")
lines.append("</div>)}")
lines.append("{regStep === 2 && (<div className=" + DQ + "space-y-3" + DQ + ">")
lines.append("<div className=" + DQ + "p-3 rounded-xl bg-blue-50/80 border border-blue-200 text-xs text-blue-900 flex items-start gap-2.5" + DQ + "><MapPin className=" + DQ + "h-5 w-5 text-blue-700 shrink-0 mt-0.5" + DQ + " /><div><strong className=" + DQ + "block text-blue-950 font-bold" + DQ + ">Enter Your Farm Location</strong><span>Type village/town name. We auto-detect lat/lng.</span></div></div>")
lines.append("<div><label className=" + DQ + "block text-xs font-bold uppercase tracking-wider text-slate-700 mb-1" + DQ + ">Place Name *</label><input type=" + DQ + "text" + DQ + " required value={regPlace} onChange={e => { setRegPlace(e.target.value); setRegLocationResolved(false); }} placeholder=" + DQ + "e.g. Baramati, Maharashtra" + DQ + " className=" + DQ + "input-field text-sm" + DQ + " />{regLocationResolved && <p className=" + DQ + "text-[11px] text-emerald-600 mt-1 flex items-center gap-1" + DQ + "><CheckCircle2 className=" + DQ + "h-3 w-3" + DQ + " /> Found: {regLat.toFixed(4)}, {regLng.toFixed(4)}</p>}</div>")
lines.append("<div className=" + DQ + "flex gap-2" + DQ + "><button type=" + DQ + "button" + DQ + " onClick={() => setRegStep(1)} className=" + DQ + "flex-1 py-3 text-sm font-bold rounded-xl border border-stone-300 text-slate-700 hover:bg-stone-50" + DQ + ">Back</button>")
lines.append("<button type=" + DQ + "button" + DQ + " onClick={async () => { if (regPlace) await geocodePlace(regPlace); }} className=" + BT + "py-3 px-4 text-sm font-bold rounded-xl border ${regLocationResolved ? " + SQ + "border-emerald-300 bg-emerald-50 text-emerald-700" + SQ + " : " + SQ + "border-blue-300 bg-blue-50 text-blue-700" + SQ + "}" + BT + ">{regLocationResolved ? " + SQ + "Resolved" + SQ + " : " + SQ + "Locate" + SQ + "}</button></div>")
lines.append("<button type=" + DQ + "button" + DQ + " onClick={() => setRegStep(3)} className=" + DQ + "btn-primary w-full py-3 text-sm font-bold bg-emerald-800 hover:bg-emerald-900" + DQ + ">Next: Farm Details</button>")
lines.append("</div>)}")
lines.append("{regStep === 3 && (<div className=" + DQ + "space-y-3" + DQ + ">")
lines.append("<div><label className=" + DQ + "block text-xs font-bold uppercase tracking-wider text-slate-700 mb-1" + DQ + ">Farm Name *</label><input type=" + DQ + "text" + DQ + " required value={regFarmName} onChange={e => setRegFarmName(e.target.value)} placeholder=" + DQ + "e.g. North Plot" + DQ + " className=" + DQ + "input-field text-sm" + DQ + " /></div>")
lines.append("<div><label className=" + DQ + "block text-xs font-bold uppercase tracking-wider text-slate-700 mb-1" + DQ + ">Farm Area (acres)</label><input type=" + DQ + "number" + DQ + " step=" + DQ + "0.1" + DQ + " value={regArea} onChange={e => setRegArea(e.target.value)} placeholder=" + DQ + "e.g. 5.0" + DQ + " className=" + DQ + "input-field text-sm" + DQ + " /></div>")
lines.append("<button type=" + DQ + "button" + DQ + " onClick={() => setRegStep(2)} className=" + DQ + "py-3 text-sm font-bold rounded-xl border border-stone-300 text-slate-700 hover:bg-stone-50 w-full" + DQ + ">Back</button>")
lines.append("<button type=" + DQ + "button" + DQ + " onClick={() => setRegStep(4)} className=" + DQ + "btn-primary w-full py-3 text-sm font-bold bg-emerald-800 hover:bg-emerald-900" + DQ + ">Next: Add Crops</button>")
lines.append("</div>)}")
lines.append("{regStep === 4 && (<div className=" + DQ + "space-y-3" + DQ + ">")
lines.append("<div className=" + DQ + "p-3 rounded-xl bg-amber-50/80 border border-amber-200 text-xs text-amber-900 flex items-start gap-2.5" + DQ + "><Sprout className=" + DQ + "h-5 w-5 text-amber-700 shrink-0 mt-0.5" + DQ + " /><div><strong className=" + DQ + "block text-amber-950 font-bold" + DQ + ">Add Your Crops</strong><span>Add at least one crop. You can add more later.</span></div></div>")
lines.append("{regCrops.length > 0 && <div className=" + DQ + "space-y-2" + DQ + ">{regCrops.map((c, i) => (<div key={i} className=" + DQ + "flex items-center justify-between p-2 rounded-lg bg-emerald-50 border border-emerald-200 text-xs" + DQ + "><span className=" + DQ + "font-bold text-emerald-900" + DQ + ">{c.cropName}" + "{c.variety ? " + DQ + " (" + DQ + " + c.variety + " + DQ + ")" + DQ + " : " + DQ + DQ + "}</span><button type=" + DQ + "button" + DQ + " onClick={() => removeCrop(i)} className=" + DQ + "text-red-500 hover:text-red-700 font-bold" + DQ + ">X</button></div>))}</div>}")
lines.append("<div className=" + DQ + "p-3 rounded-xl bg-stone-50 border border-stone-200 space-y-2" + DQ + ">")
lines.append("<div className=" + DQ + "grid grid-cols-2 gap-2" + DQ + "><div><label className=" + DQ + "block text-[10px] font-bold uppercase text-slate-600 mb-0.5" + DQ + ">Crop Name *</label><input type=" + DQ + "text" + DQ + " value={regCropName} onChan
