import sys
Q = chr(39)
D = chr(34)
def q(s): return Q+s+Q
def d(s): return D+s+D
lines = []
a = lines.append
a("import React, { useEffect, useState } from " + q("react") + ";")
a("import { farmService, Farm, Crop } from " + q("../services/farmService") + ";")
a("import { PageHeader } from " + q("../components/common/PageHeader") + ";")
a("import { Modal } from " + q("../components/common/Modal") + ";")
a("import { Sprout, Plus, Search, MapPin, Trash2 } from " + q("lucide-react") + ";")
a("import { Link } from " + q("react-router-dom") + ";")
a("import { useAuth } from " + q("../context/AuthContext") + ";")
a("")
a("export const MyFarmsPage: React.FC = () => {")
a("  const { user } = useAuth();")
a("  const [farms, setFarms] = useState<Farm[]>([]);")
a("  const [isLoading, setIsLoading] = useState(true);")
a("  const [searchTerm, setSearchTerm] = useState('');")
a("  const [isAddFarmOpen, setIsAddFarmOpen] = useState(false);")
a("  const [farmName, setFarmName] = useState('');")
a("  const [farmLocation, setFarmLocation] = useState('');")
a("  const [farmArea, setFarmArea] = useState('');")
a("  const [isAddCropOpen, setIsAddCropOpen] = useState(false);")
a("  const [selectedFarmId, setSelectedFarmId] = useState('');")
a("  const [cropName, setCropName] = useState('Tomato');")
a("  const [cropVariety, setCropVariety] = useState('');")
a("  const [cropAcreage, setCropAcreage] = useState('');")
a("")
a("  const loadFarms = async () => {")
a("    setIsLoading(true);")
a("    const res = await farmService.getMyFarms();")
a("    if (res.data) setFarms(res.data);")
a("    setIsLoading(false);")
a("  };")
a("")
a("  useEffect(() => { loadFarms(); }, []);")
a("")
a("  const handleAddFarm = async (e: React.FormEvent) => {")
a("    e.preventDefault();")
a("    await farmService.createFarm({ farmName, location: farmLocation, latitude: 0, longitude: 0, area: parseFloat(farmArea) || 0 });")
a("    setFarmName(''); setFarmLocation(''); setFarmArea('');")
a("    setIsAddFarmOpen(false); loadFarms();")
a("  };")
a("")
a("  const handleAddCrop = async (e: React.FormEvent) => {")
a("    e.preventDefault();")
a("    await farmService.addCrop(selectedFarmId, { cropName, variety: cropVariety || undefined, acreage: parseFloat(cropAcreage) || 0 });")
a("    setCropName('Tomato'); setCropVariety(''); setCropAcreage('');")
a("    setIsAddCropOpen(false); loadFarms();")
a("  };")
a("")
a("  const handleRemoveCrop = async (farmId: string, cropId: string) => {")
a("    if (!confirm('Remove this crop?')) return;")
a("    await farmService.removeCrop(farmId, cropId);")
a("    loadFarms();")
a("  };")
a("")
a("  const openAddCrop = (farmId: string) => { setSelectedFarmId(farmId); setIsAddCropOpen(true); };")
a("")
a("  const filteredFarms = farms.filter(f =>")
a("    f.farmName.toLowerCase().includes(searchTerm.toLowerCase()) ||")
a("    f.location.toLowerCase().includes(searchTerm.toLowerCase()) ||")
a("    (f.crops || []).some(c => c.cropName.toLowerCase().includes(searchTerm.toLowerCase()))")
a("  );")
a("")
a("  return (")
a("    <div className=" + d("space-y-6") + ">")
a("      <PageHeader title=" + d("My Farms") + " subtitle=" + d("Manage your farms and crops") + " action={<button onClick={() => setIsAddFarmOpen(true)} className=" + d("btn-primary") + "><Plus className=" + d("h-4 w-4") + "/> Add Farm</button>} />")
a("      <div className=" + d("card p-4") + "><div className=" + d("relative") + "><Search className=" + d("absolute left-3.5 top-1/2 -translate-y-1/2 h-4 w-4 text-slate-400") + "/><input type=" + d("text") + " value={searchTerm} onChange={e => setSearchTerm(e.target.value)} placeholder=" + d("Search farms or crops...") + " className=" + d("input-field pl-10") + "/></div></div>")
a("      {isLoading ? <div className=" + d("text-center py-12 text-slate-500 text-sm") + ">Loading...</div> :")
a("       filteredFarms.length === 0 ? <div className=" + d("text-center py-12") + "><Sprout className=" + d("h-12 w-12 text-slate-300 mx-auto") + "/><p className=" + d("text-sm text-slate-500 mt-2") + ">No farms yet.</p></div> :")
a("       <div className=" + d("grid grid-cols-1 md:grid-cols-2 gap-5") + ">")
a("        {filteredFarms.map(farm => (")
a("          <div key={farm._id} className=" + d("card p-6 space-y-4") + ">")
a("            <div className=" + d("flex items-start justify-between") + ">")
a("              <div><h3 className=" + d("text-base font-bold text-slate-900") + ">{farm.farmName}</h3>")
a("              <p className=" + d("text-xs text-slate-500") + "><MapPin className=" + d("h-3.5 w-3.5 text-agri-600") + "/> {farm.location || 'No location'}</p></div>")
a("              <span className=" + d("text-xs font-bold text-slate-600 bg-stone-100 px-2 py-1 rounded-lg") + ">{farm.area || 0} {farm.areaUnit || 'acres'}</span>")
a("            </div>")
a("            <div className=" + d("space-y-2") + ">")
a("              <div className=" + d("flex items-center justify-between") + ">")
a("                <span className=" + d("text-xs font-bold uppercase tracking-wider text-slate-500") + ">Crops</span>")
a("                <button onClick={() => openAddCrop(farm._id)} className=" + d("text-xs font-bold text-agri-700 hover:text-agri-900 flex items-center gap-1") + "><Plus className=" + d("h-3.5 w-3.5") + "/> Add Crop</button>")
a("              </div>")
a("              {(farm.crops || []).length === 0 ? <p className=" + d("text-xs text-slate-400 italic") + ">No crops yet</p> :")
a("               (farm.crops || []).map(crop => (")
a("                <div key={crop._id} className=" + d("flex items-center justify-between p-2.5 rounded-xl bg-stone-50 border border-stone-200") + ">")
a("                  <div><span className=" + d("text-sm font-bold text-slate-900") + ">{crop.cropName}</span>")
a("                  {crop.variety && <span className=" + d("text-xs text-slate-500 ml-2") + "> ({crop.variety})</span>}")
a("                  {crop.acreage > 0 && <span className=" + d("text-xs text-slate-400 ml-2") + "> {crop.acreage} ac</span>}</div>")
a("                  <button onClick={() => handleRemoveCrop(farm._id, crop._id)} className=" + d("text-red-400 hover:text-red-600 p-1") + "><Trash2 className=" + d("h-3.5 w-3.5") + "/></button>")
a("                </div>)))}")
a("            </div>")
a("            <div className=" + d("pt-3 border-t border-stone-100") + ">")
a("              <Link to=" + d("/farmer/disease-detection") + " className=" + d("rounded-xl bg-agri-50 border border-agri-300 px-3 py-1.5 text-xs font-bold text-agri-800 inline-flex items-center gap-1") + "><Sprout className=" + d("h-3.5 w-3.5") + "/> Scan Crop</Link>")
a("            </div>")
a("          </div>))}")
a("       </div>}")
a("      <Modal isOpen={isAddFarmOpen} onClose={() => setIsAddFarmOpen(false)} title=" + d("Add New Farm") + " subtitle=" + d("Register a new farm plot") + ">")
a("        <form onSubmit={handleAddFarm} className=" + d("space-y-4") + ">")
a("          <div><label className=" + d("block text-xs font-bold uppercase tracking-wider text-slate-700 mb-1") + ">Farm Name *</label><input type=" + d("text") + " required value={farmName} onChange={e => setFarmName(e.target.value)} className=" + d("input-field") + "/></div>")
a("          <div><label className=" + d("block text-xs font-bold uppercase tracking-wider text-slate-700 mb-1") + ">Location *</label><input type=" + d("text") + " required value={farmLocation} onChange={e => setFarmLocation(e.target.value)} className=" + d("input-field") + "/></div>")
a("          <div><label className=" + d("block text-xs font-bold uppercase tracking-wider text-slate-700 mb-1") + ">Area (acres)</label><input type=" + d("number") + " step=" + d("0.1") + " value={farmArea} onChange={e => setFarmArea(e.target.value)} className=" + d("input-field") + "/></div>")
a("          <div className=" + d("flex justify-end gap-3 pt-3 border-t border-stone-100") + "><button type=" + d("button") + " onClick={() =
